In [56]:
import numpy as np
import random

def tableauBase(P):
     
    tableau_de_zero_un = np.zeros((10,10), dtype='i')
    for i in range(len(tableau_de_zero_un)):
        for j in range(len(tableau_de_zero_un)):
            if random.random() < P :
                tableau_de_zero_un[i,j] = 1
    print("\n\n\t\t VILLE BASIQUE\n\n\n")
    return (tableau_de_zero_un)
    
tableauBase(0.5)



		 VILLE BASIQUE





array([[0, 0, 1, 0, 1, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 1, 0, 0, 1, 1, 0],
       [1, 1, 1, 0, 1, 1, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 0, 1],
       [0, 1, 0, 1, 0, 0, 1, 0, 1, 1],
       [1, 1, 0, 0, 0, 1, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 1, 0, 0, 1, 1],
       [1, 1, 0, 0, 0, 1, 1, 1, 1, 1],
       [0, 1, 0, 0, 1, 1, 0, 1, 0, 1]], dtype=int32)

In [90]:
def creationDeGang(P):
    """H: nous voulons savoir si un carré crée un groupe de gang (nommé 3)"""
    
    tableau = tableauBase(P)
    print (tableau)
    for i in range(len(tableau)) :
        for j in range(len(tableau)) :
            if  i+1 < len(tableau) and i-1 >= 0 and  j+1 < len(tableau) and j-1 >= 0:
                 if tableau[i,j] == 0 and tableau[i+1,j]==0  and tableau[i,j+1]==0 and tableau[i+1,j+1]==0 :
                    
                    tableau[i,j] = 3
                    tableau[i+1,j]=3  
     
                    tableau[i,j+1]=3
                    tableau[i+1,j+1]=3
                    
    print("\n\n\t\t VILLE AVEC GANG\n\n\n")
    return tableau
#modifier le programme refaire tt et montrer a chaque fois qu'il y a un changement ,ajouter aussi que les riche parte quand il y a un gang (1 = 0)
creationDeGang(0.5)



		 VILLE BASIQUE



[[0 1 0 1 0 0 0 0 1 0]
 [1 1 0 1 1 1 0 1 0 0]
 [0 1 0 1 1 0 0 0 1 0]
 [1 1 0 1 0 1 1 0 1 0]
 [0 0 1 0 0 0 0 1 0 1]
 [1 0 0 0 1 0 0 1 0 0]
 [0 0 0 0 1 0 0 1 1 0]
 [0 0 0 0 0 1 1 0 0 0]
 [0 1 0 1 0 1 0 0 0 0]
 [0 1 1 1 0 1 0 1 0 0]]


		 VILLE AVEC GANG





array([[0, 1, 0, 1, 0, 0, 0, 0, 1, 0],
       [1, 1, 0, 1, 1, 1, 0, 1, 0, 0],
       [0, 1, 0, 1, 1, 0, 0, 0, 1, 0],
       [1, 1, 0, 1, 0, 1, 1, 0, 1, 0],
       [0, 0, 1, 0, 0, 3, 3, 1, 0, 1],
       [1, 3, 3, 0, 1, 3, 3, 1, 0, 0],
       [0, 3, 3, 0, 1, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 1, 1, 3, 3, 0],
       [0, 1, 0, 1, 0, 1, 0, 3, 3, 0],
       [0, 1, 1, 1, 0, 1, 0, 1, 0, 0]], dtype=int32)

***On remarque que il y a des gangs qui se crée peu a peu dut a la grande presece de 0 (de pauvreté)***

In [121]:
def creationInfluenceDeGang(P):
    
    tableau= creationDeGang(P)
    
    print(tableau)
    for i in range(len(tableau)) :
        for j in range(len(tableau)) :
             if  i+1 < len(tableau) and i-1 >= 0 and  j+1 < len(tableau) and j-1 >= 0 :    
                
                    if tableau[i,j-1] == 1 :
                        tableau[i,j-1] == 0
                                
                    elif tableau[i+1,j] == 1 :
                        tableau[i+1,j] == 0
                                
                    elif tableau[i,j+1] == 1 :
                        tableau[i,j+1] == 0
                                    
                    elif tableau[i-1,j] == 1 :
                        tableau[i-1,j] == 0
    
    print("\n\n\t\t REACTION HABITANT\n\n\n")
    return tableau
#ne se change pas verifier
creationInfluenceDeGang(0.5)



		 VILLE BASIQUE



[[1 0 0 1 1 0 1 1 0 1]
 [1 1 1 0 0 1 1 0 1 0]
 [1 1 1 0 0 0 0 0 1 0]
 [1 0 1 1 0 1 1 1 1 0]
 [1 1 1 0 0 0 0 1 0 1]
 [1 0 0 0 1 0 1 0 0 0]
 [0 0 0 1 1 0 1 0 0 1]
 [1 1 0 1 0 0 1 0 0 0]
 [0 1 1 1 0 0 1 1 1 0]
 [1 1 0 1 0 0 0 0 0 0]]


		 VILLE AVEC GANG



[[1 0 0 1 1 0 1 1 0 1]
 [1 1 1 3 3 1 1 0 1 0]
 [1 1 1 3 3 0 0 0 1 0]
 [1 0 1 1 0 1 1 1 1 0]
 [1 1 1 0 0 0 0 1 0 1]
 [1 3 3 0 1 0 1 3 3 0]
 [0 3 3 1 1 0 1 3 3 1]
 [1 1 0 1 3 3 1 0 0 0]
 [0 1 1 1 3 3 1 1 1 0]
 [1 1 0 1 0 0 0 0 0 0]]


		 REACTION HABITANT





array([[1, 0, 0, 1, 1, 0, 1, 1, 0, 1],
       [1, 1, 1, 3, 3, 1, 1, 0, 1, 0],
       [1, 1, 1, 3, 3, 0, 0, 0, 1, 0],
       [1, 0, 1, 1, 0, 1, 1, 1, 1, 0],
       [1, 1, 1, 0, 0, 0, 0, 1, 0, 1],
       [1, 3, 3, 0, 1, 0, 1, 3, 3, 0],
       [0, 3, 3, 1, 1, 0, 1, 3, 3, 1],
       [1, 1, 0, 1, 3, 3, 1, 0, 0, 0],
       [0, 1, 1, 1, 3, 3, 1, 1, 1, 0],
       [1, 1, 0, 1, 0, 0, 0, 0, 0, 0]], dtype=int32)