In [83]:
import numpy as np
import random

def tableauBase(P):
     
    tableau_de_zero = np.zeros((10,10), dtype='i')
    for i in range(len(tableau_de_zero)):
        for j in range(len(tableau_de_zero)):
            if random.random() < P :
                tableau_de_zero[i,j] = 1
            
    return (tableau_de_zero)
    
tableauBase(0.5)

array([[1, 0, 0, 0, 1, 1, 1, 0, 0, 0],
       [0, 1, 1, 1, 0, 1, 1, 1, 1, 1],
       [0, 1, 1, 0, 1, 1, 0, 0, 1, 1],
       [1, 0, 1, 1, 0, 0, 0, 1, 1, 1],
       [0, 1, 1, 0, 1, 1, 1, 1, 0, 1],
       [0, 1, 1, 1, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 0, 1, 1, 1],
       [1, 1, 1, 1, 0, 0, 1, 0, 1, 1],
       [1, 1, 1, 0, 1, 1, 0, 0, 0, 0]], dtype=int32)

In [89]:
def creationDeGang(P):
    """H: nous voulons savoir si un carré crée un groupe de gang (nommé 3)"""
    
    tableau = tableauBase(P)
    print (tableau)
    for i in range(len(tableau)) :
        for j in range(len(tableau)) :
            if  i+1 < len(tableau) and i-1 >= 0:
                 if tableau[i,j] == 0 and tableau[i+1,j]==0  and tableau[i+1,j+1]==0 and tableau[i,j+1] :
                    tableau[i,j] = 3
                    tableau[i+1,j]=3  
                    tableau[i-1,j] =3 
                    tableau[i,j-1]=3
                    tableau[i,j+1]=3
                    
            """"if j+3 < len(tableau):
                if tableau[i,j] == 0 and tableau[i,j+1] == 0 and tableau [i, j+2] == 0 and tableau[i,j+3] == 0 : 
                    tableau [i,j] = 3
                    tableau [i,j+1] = 3
                    tableau [i,j+2] = 3
                    tableau [i, j+3] = 3"""
    return tableau
#modifier le programme refaire tt et montrer a chaque fois qu'il y a un changement ,ajouter aussi que les riche parte quand il y a un gang (1 = 0)
creationDeGang(0.5)

[[1 0 1 1 0 1 0 0 0 1]
 [0 0 0 1 0 1 0 1 1 1]
 [0 1 1 0 0 0 1 0 0 0]
 [1 0 0 0 1 1 0 1 0 1]
 [1 1 0 0 1 0 1 0 1 0]
 [0 0 0 0 1 0 1 0 0 1]
 [1 1 0 0 1 0 1 1 1 0]
 [1 0 1 1 1 0 0 1 1 1]
 [1 1 0 0 0 1 1 0 1 0]
 [1 0 0 0 0 0 0 1 0 1]]


array([[1, 0, 1, 1, 3, 1, 0, 0, 0, 1],
       [0, 0, 0, 3, 3, 3, 0, 1, 1, 1],
       [0, 1, 1, 0, 3, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 1, 0, 3, 0, 1],
       [1, 1, 0, 0, 1, 0, 3, 3, 3, 0],
       [0, 0, 0, 0, 1, 3, 1, 3, 0, 1],
       [1, 1, 0, 0, 3, 3, 3, 1, 1, 0],
       [1, 0, 1, 1, 3, 3, 0, 1, 1, 1],
       [1, 1, 0, 3, 3, 3, 1, 0, 1, 0],
       [1, 0, 0, 0, 3, 0, 0, 1, 0, 1]], dtype=int32)